### ISSUE TITLE
Adding map presets using event-decision system

### ISSUE THREAD

**Issue by fleeingmoth** [Unperson70/ahgoverhaul#10]
Since it is difficult to use other bookmarks to have other maps, you could have the same function using decisions.
Considering the decisions menu is still possible to access, you could possibly have decisions that set the world to a specific preset by making a decision (or event that ties to one) that hands over land to the specific country.
You could create ones that mirrored: 2000, every lake and canal existing, and possibly other historical time periods. I think a 2000 map would be most useful as it would make Africa and India less tedious to make look historical. Additionally, this would solve the question of what counts of a lake if it's simply defined in the decision that transfers all lakes to the water country.

**Comment by Pcola129** [comment]
that's.. actually a good idea.
